# Generated by Django 4.1.1 on 2022-09-16 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0002_profilefeeditem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profilefeeditem',
            old_name='status_text',
            new_name='message',
        ),
    ]
