# Generated by Django 4.1.1 on 2022-09-16 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0003_rename_status_text_profilefeeditem_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profilefeeditem',
            old_name='created_on',
            new_name='date',
        ),
    ]
