# Generated by Django 4.1.1 on 2022-09-16 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0004_rename_created_on_profilefeeditem_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profilefeeditem',
            old_name='date',
            new_name='timestamp',
        ),
    ]
