# Generated by Django 4.1.1 on 2022-09-16 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0005_rename_date_profilefeeditem_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilefeeditem',
            name='destination',
            field=models.CharField(default='test', max_length=255),
            preserve_default=False,
        ),
    ]
