# Generated by Django 4.1.1 on 2022-09-20 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0006_profilefeeditem_destination'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProfileFeedItem',
        ),
    ]
